# Generated by Django 4.1.3 on 2022-12-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather2', '0002_alter_home_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
