# Generated by Django 4.1.3 on 2022-12-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather2', '0003_home_city_alter_home_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField()),
                ('img', models.ImageField(upload_to='hour_images')),
                ('wind', models.IntegerField()),
                ('dewpoint', models.IntegerField()),
                ('visibility', models.IntegerField()),
            ],
        ),
    ]
