# Generated by Django 4.1.3 on 2022-12-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather2', '0004_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('image', models.ImageField(upload_to='daily_images')),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
            ],
        ),
    ]
