# Generated by Django 4.1.3 on 2022-12-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather2', '0005_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='month_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uv', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('windgusts', models.IntegerField()),
                ('cloudcover', models.IntegerField()),
                ('degree', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='month_night',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uv', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('windgusts', models.IntegerField()),
                ('cloudcover', models.IntegerField()),
                ('degree', models.IntegerField()),
            ],
        ),
    ]
